/**
* WhoseHouse
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param id 
 * @param issueId 
 * @param technicianId 
 * @param createdAt 
 */
data class AcceptedIssueSyncDto (
    val id: kotlin.Long,
    val issueId: kotlin.Long,
    val technicianId: kotlin.Long,
    val createdAt: java.time.LocalDateTime
) 

