/**
* WhoseHouse
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param id 
 * @param externalId 
 * @param status 
 * @param updatedAt 
 * @param createdAt 
 * @param contactPerson 
 * @param address 
 * @param description 
 * @param note 
 * @param latestAssignmentDate 
 */
data class IssueSyncDto (
    val id: kotlin.Long,
    val externalId: kotlin.Long,
    val status: kotlin.String,
    val updatedAt: java.time.LocalDateTime,
    val createdAt: java.time.LocalDateTime,
    val contactPerson: kotlin.String? = null,
    val address: kotlin.String? = null,
    val description: kotlin.String? = null,
    val note: kotlin.String? = null,
    val latestAssignmentDate: java.time.LocalDateTime? = null
) 

