/**
* WhoseHouse
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param issues 
 * @param technicians 
 * @param acceptedIssues 
 * @param latestTimestamp 
 */
data class SyncResponse (
    val issues: kotlin.Array<kotlin.Any>,
    val technicians: kotlin.Array<kotlin.Any>,
    val acceptedIssues: kotlin.Array<kotlin.Any>,
    val latestTimestamp: java.time.LocalDateTime? = null
) 

