/**
* WhoseHouse
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
* 
* Values: INSERTED,UPDATED,DELETED
*/
enum class SyncStatus(val value: kotlin.String){

    INSERTED("INSERTED"),

    UPDATED("UPDATED"),

    DELETED("DELETED");

}

