/**
* WhoseHouse
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param syncStatus 
 * @param technician 
 */
data class TechnicianWrapperSyncDto (
    val syncStatus: kotlin.Any,
    val technician: kotlin.Any? = null
) 

